#!/bin/bash

#Libraries need a ldconfig

ldconfig

useradd -m pi

gpasswd -a pi video

echo "allowed_users=anybody" > /etc/X11/Xwrapper.config

cp /app/xinitrc /home/pi/.xinitrc;
chown pi: /home/pi/.xinitrc

echo "RESIN_DEVICE_ID: ${RESIN_DEVICE_UUID}"

export SCREENORAMA_URL="http://screenorama-dev.herokuapp.com/${RESIN_DEVICE_UUID}"
echo "SCREENORAMA_URL: ${SCREENORAMA_URL}"

cp -r /app/web_assets /home/pi/web_assets
cp /app/boot/config.txt /boot/config.txt

sync

sed -i "s|SCREENORAMA_URL|$SCREENORAMA_URL|g" /home/pi/web_assets/index.html

chown -R pi: /home/pi/web_assets

sync

su - pi -c startx &
